const actionTypes = Object.freeze({
    // App
    APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

    //user
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_LOGOUT: "USER_LOGOUT",

    GET_ITEM_CART_SUCCESS: "GET_ITEM_CART_SUCCESS",
    GET_ITEM_CART_FAILED: "GET_ITEM_CART_FAILED",

    DELETE_ALL_ITEM_CART_SUCCESS: "DELETE_ALL_ITEM_CART_SUCCESS",
    DELETE_ALL_ITEM_CART_FAILED: "DELETE_ALL_ITEM_CART_FAILED",

    DELETE_A_ITEM_CART_SUCCESS: "DELETE_A_ITEM_CART_SUCCESS",
    DELETE_A_ITEM_CART_FAILED: "DELETE_A_ITEM_CART_FAILED",
});

export default actionTypes;
